#!/bin/bash

# TODO: generate this file... termite should handle it!
SCRIPT=/usr/local/bin/DNS
cat > $SCRIPT <<EOM
#!/bin/bash

node $(pwd)/DNS.js \$@

EOM
chmod +x $SCRIPT
# And that should do it!
echo "INSTALLED @ $SCRIPT"
